# Generated by Django 3.2 on 2024-10-26 01:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='patente',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='Formato de patente inválido. Debe seguir el patrón AA-BB12.', regex='^[A-Z]{2}-[A-Z]{2}\\d{2}$')]),
        ),
    ]
